### PR TITLE
feat: Adding Flowbite as Frontend option

### PR DESCRIPTION
**Pull request by nea**
**What this PR is changing or adding?**

Ahoy there

First of all: Great tool!

As I fiddled around and created some projects with gowebly, I wanted to leverage (Flowbite)[https://flowbite.com/] on top of Tailwind and added it manually. 

So, I thought I add it to gowebly directly. This would be the PR.

If you would like to skip it or have it differently, just let me know.

Thanks and Best

**Before/after or any other screenshots**

No differences

**Which issues are fixed by this PR?**

1. No direct issue, just a "personal issue" of starting with Flowbite every time

## Pre-launch Checklist

- [x] I have read and fully accepted project's [code of conduct][repo_coc_url].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation and/or comments to the code.
- [x] All existing and new tests are passing successfully.

[repo_coc_url]: https://github.com/gowebly/.github/blob/main/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by koddr** [comment]
Hi, @nea 

Thank you for this PR and warm words!

Do you have a chance to cover this (and more) Gowebly code with tests? That would be very welcome.

**Comment by nea** [comment]
Ahoy @koddr 

I was already looking into that. From what I can see, also with the DI, a lot of mocking and potentially additional configuration properties would be necessary to really test the commands properly.
As there is eventually a lot of file and folder creation, that would have to be redirected or based in a tmp folder, as you also do in the download test, to clear it post-test, or split up per command to just test the logic properly. But for that, I do not see an argument right now, so this would have to be added.

I will try and add some helper and smaller tests where feasible.
For the command testing I suggest doing a smaller refactoring first to be able to separate logic and parameters a little, so that it is easier to validate.


Best

**Comment by nea** [comment]
Ahoy @koddr 

I added tests for the `file_system.go` and `embed_file_system.go` helpers now.
It's more or less standard unit testing of these helpers to further complete the helpers structure.
That is all I can bring to the table for now time-wise. 
Let me know, if it is ok.

For the overall testing, I would still suggest a structural break up first.


Best and have some calm days :)

**Comment by koddr** [comment]
Hi, @nea 

Wow! Amazing work, thank you. 😊

Merge this PR to `v1.10.0` release.

**Pull request merged**
